// This file is generated by rust-protobuf 2.27.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `gogoproto/gogo.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_27_1;

/// Extension fields
pub mod exts {

    pub const goproto_enum_prefix: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 62001, phantom: ::std::marker::PhantomData };

    pub const goproto_enum_stringer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 62021, phantom: ::std::marker::PhantomData };

    pub const enum_stringer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 62022, phantom: ::std::marker::PhantomData };

    pub const enum_customname: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumOptions, ::protobuf::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 62023, phantom: ::std::marker::PhantomData };

    pub const enumdecl: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 62024, phantom: ::std::marker::PhantomData };

    pub const enumvalue_customname: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::EnumValueOptions, ::protobuf::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 66001, phantom: ::std::marker::PhantomData };

    pub const goproto_getters_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63001, phantom: ::std::marker::PhantomData };

    pub const goproto_enum_prefix_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63002, phantom: ::std::marker::PhantomData };

    pub const goproto_stringer_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63003, phantom: ::std::marker::PhantomData };

    pub const verbose_equal_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63004, phantom: ::std::marker::PhantomData };

    pub const face_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63005, phantom: ::std::marker::PhantomData };

    pub const gostring_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63006, phantom: ::std::marker::PhantomData };

    pub const populate_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63007, phantom: ::std::marker::PhantomData };

    pub const stringer_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63008, phantom: ::std::marker::PhantomData };

    pub const onlyone_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63009, phantom: ::std::marker::PhantomData };

    pub const equal_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63013, phantom: ::std::marker::PhantomData };

    pub const description_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63014, phantom: ::std::marker::PhantomData };

    pub const testgen_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63015, phantom: ::std::marker::PhantomData };

    pub const benchgen_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63016, phantom: ::std::marker::PhantomData };

    pub const marshaler_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63017, phantom: ::std::marker::PhantomData };

    pub const unmarshaler_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63018, phantom: ::std::marker::PhantomData };

    pub const stable_marshaler_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63019, phantom: ::std::marker::PhantomData };

    pub const sizer_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63020, phantom: ::std::marker::PhantomData };

    pub const goproto_enum_stringer_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63021, phantom: ::std::marker::PhantomData };

    pub const enum_stringer_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63022, phantom: ::std::marker::PhantomData };

    pub const unsafe_marshaler_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63023, phantom: ::std::marker::PhantomData };

    pub const unsafe_unmarshaler_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63024, phantom: ::std::marker::PhantomData };

    pub const goproto_extensions_map_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63025, phantom: ::std::marker::PhantomData };

    pub const goproto_unrecognized_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63026, phantom: ::std::marker::PhantomData };

    pub const gogoproto_import: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63027, phantom: ::std::marker::PhantomData };

    pub const protosizer_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63028, phantom: ::std::marker::PhantomData };

    pub const compare_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63029, phantom: ::std::marker::PhantomData };

    pub const typedecl_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63030, phantom: ::std::marker::PhantomData };

    pub const enumdecl_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63031, phantom: ::std::marker::PhantomData };

    pub const goproto_registration: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63032, phantom: ::std::marker::PhantomData };

    pub const messagename_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63033, phantom: ::std::marker::PhantomData };

    pub const goproto_sizecache_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63034, phantom: ::std::marker::PhantomData };

    pub const goproto_unkeyed_all: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FileOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 63035, phantom: ::std::marker::PhantomData };

    pub const goproto_getters: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64001, phantom: ::std::marker::PhantomData };

    pub const goproto_stringer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64003, phantom: ::std::marker::PhantomData };

    pub const verbose_equal: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64004, phantom: ::std::marker::PhantomData };

    pub const face: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64005, phantom: ::std::marker::PhantomData };

    pub const gostring: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64006, phantom: ::std::marker::PhantomData };

    pub const populate: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64007, phantom: ::std::marker::PhantomData };

    pub const stringer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 67008, phantom: ::std::marker::PhantomData };

    pub const onlyone: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64009, phantom: ::std::marker::PhantomData };

    pub const equal: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64013, phantom: ::std::marker::PhantomData };

    pub const description: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64014, phantom: ::std::marker::PhantomData };

    pub const testgen: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64015, phantom: ::std::marker::PhantomData };

    pub const benchgen: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64016, phantom: ::std::marker::PhantomData };

    pub const marshaler: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64017, phantom: ::std::marker::PhantomData };

    pub const unmarshaler: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64018, phantom: ::std::marker::PhantomData };

    pub const stable_marshaler: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64019, phantom: ::std::marker::PhantomData };

    pub const sizer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64020, phantom: ::std::marker::PhantomData };

    pub const unsafe_marshaler: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64023, phantom: ::std::marker::PhantomData };

    pub const unsafe_unmarshaler: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64024, phantom: ::std::marker::PhantomData };

    pub const goproto_extensions_map: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64025, phantom: ::std::marker::PhantomData };

    pub const goproto_unrecognized: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64026, phantom: ::std::marker::PhantomData };

    pub const protosizer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64028, phantom: ::std::marker::PhantomData };

    pub const compare: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64029, phantom: ::std::marker::PhantomData };

    pub const typedecl: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64030, phantom: ::std::marker::PhantomData };

    pub const messagename: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64033, phantom: ::std::marker::PhantomData };

    pub const goproto_sizecache: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64034, phantom: ::std::marker::PhantomData };

    pub const goproto_unkeyed: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::MessageOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 64035, phantom: ::std::marker::PhantomData };

    pub const nullable: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 65001, phantom: ::std::marker::PhantomData };

    pub const embed: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 65002, phantom: ::std::marker::PhantomData };

    pub const customtype: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 65003, phantom: ::std::marker::PhantomData };

    pub const customname: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 65004, phantom: ::std::marker::PhantomData };

    pub const jsontag: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 65005, phantom: ::std::marker::PhantomData };

    pub const moretags: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 65006, phantom: ::std::marker::PhantomData };

    pub const casttype: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 65007, phantom: ::std::marker::PhantomData };

    pub const castkey: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 65008, phantom: ::std::marker::PhantomData };

    pub const castvalue: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeString> = ::protobuf::ext::ExtFieldOptional { field_number: 65009, phantom: ::std::marker::PhantomData };

    pub const stdtime: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 65010, phantom: ::std::marker::PhantomData };

    pub const stdduration: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 65011, phantom: ::std::marker::PhantomData };

    pub const wktpointer: ::protobuf::ext::ExtFieldOptional<::protobuf::descriptor::FieldOptions, ::protobuf::types::ProtobufTypeBool> = ::protobuf::ext::ExtFieldOptional { field_number: 65012, phantom: ::std::marker::PhantomData };
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x14gogoproto/gogo.proto\x12\tgogoproto\x1a\x20google/protobuf/descrip\
    tor.proto:P\n\x13goproto_enum_prefix\x18\xb1\xe4\x03\x20\x01(\x08\x12\
    \x1c.google.protobuf.EnumOptionsR\x11goprotoEnumPrefixB\0:T\n\x15goproto\
    _enum_stringer\x18\xc5\xe4\x03\x20\x01(\x08\x12\x1c.google.protobuf.Enum\
    OptionsR\x13goprotoEnumStringerB\0:E\n\renum_stringer\x18\xc6\xe4\x03\
    \x20\x01(\x08\x12\x1c.google.protobuf.EnumOptionsR\x0cenumStringerB\0:I\
    \n\x0fenum_customname\x18\xc7\xe4\x03\x20\x01(\t\x12\x1c.google.protobuf\
    .EnumOptionsR\x0eenumCustomnameB\0:<\n\x08enumdecl\x18\xc8\xe4\x03\x20\
    \x01(\x08\x12\x1c.google.protobuf.EnumOptionsR\x08enumdeclB\0:X\n\x14enu\
    mvalue_customname\x18\xd1\x83\x04\x20\x01(\t\x12!.google.protobuf.EnumVa\
    lueOptionsR\x13enumvalueCustomnameB\0:P\n\x13goproto_getters_all\x18\x99\
    \xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x11goprotoGet\
    tersAllB\0:W\n\x17goproto_enum_prefix_all\x18\x9a\xec\x03\x20\x01(\x08\
    \x12\x1c.google.protobuf.FileOptionsR\x14goprotoEnumPrefixAllB\0:R\n\x14\
    goproto_stringer_all\x18\x9b\xec\x03\x20\x01(\x08\x12\x1c.google.protobu\
    f.FileOptionsR\x12goprotoStringerAllB\0:L\n\x11verbose_equal_all\x18\x9c\
    \xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x0fverboseEqu\
    alAllB\0:;\n\x08face_all\x18\x9d\xec\x03\x20\x01(\x08\x12\x1c.google.pro\
    tobuf.FileOptionsR\x07faceAllB\0:C\n\x0cgostring_all\x18\x9e\xec\x03\x20\
    \x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x0bgostringAllB\0:C\n\x0c\
    populate_all\x18\x9f\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOp\
    tionsR\x0bpopulateAllB\0:C\n\x0cstringer_all\x18\xa0\xec\x03\x20\x01(\
    \x08\x12\x1c.google.protobuf.FileOptionsR\x0bstringerAllB\0:A\n\x0bonlyo\
    ne_all\x18\xa1\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\
    \nonlyoneAllB\0:=\n\tequal_all\x18\xa5\xec\x03\x20\x01(\x08\x12\x1c.goog\
    le.protobuf.FileOptionsR\x08equalAllB\0:I\n\x0fdescription_all\x18\xa6\
    \xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x0edescriptio\
    nAllB\0:A\n\x0btestgen_all\x18\xa7\xec\x03\x20\x01(\x08\x12\x1c.google.p\
    rotobuf.FileOptionsR\ntestgenAllB\0:C\n\x0cbenchgen_all\x18\xa8\xec\x03\
    \x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x0bbenchgenAllB\0:E\n\
    \rmarshaler_all\x18\xa9\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.Fil\
    eOptionsR\x0cmarshalerAllB\0:I\n\x0funmarshaler_all\x18\xaa\xec\x03\x20\
    \x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x0eunmarshalerAllB\0:R\n\
    \x14stable_marshaler_all\x18\xab\xec\x03\x20\x01(\x08\x12\x1c.google.pro\
    tobuf.FileOptionsR\x12stableMarshalerAllB\0:=\n\tsizer_all\x18\xac\xec\
    \x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x08sizerAllB\0:[\
    \n\x19goproto_enum_stringer_all\x18\xad\xec\x03\x20\x01(\x08\x12\x1c.goo\
    gle.protobuf.FileOptionsR\x16goprotoEnumStringerAllB\0:L\n\x11enum_strin\
    ger_all\x18\xae\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptions\
    R\x0fenumStringerAllB\0:R\n\x14unsafe_marshaler_all\x18\xaf\xec\x03\x20\
    \x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x12unsafeMarshalerAllB\0:\
    V\n\x16unsafe_unmarshaler_all\x18\xb0\xec\x03\x20\x01(\x08\x12\x1c.googl\
    e.protobuf.FileOptionsR\x14unsafeUnmarshalerAllB\0:]\n\x1agoproto_extens\
    ions_map_all\x18\xb1\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOp\
    tionsR\x17goprotoExtensionsMapAllB\0:Z\n\x18goproto_unrecognized_all\x18\
    \xb2\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x16goprot\
    oUnrecognizedAllB\0:K\n\x10gogoproto_import\x18\xb3\xec\x03\x20\x01(\x08\
    \x12\x1c.google.protobuf.FileOptionsR\x0fgogoprotoImportB\0:G\n\x0eproto\
    sizer_all\x18\xb4\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptio\
    nsR\rprotosizerAllB\0:A\n\x0bcompare_all\x18\xb5\xec\x03\x20\x01(\x08\
    \x12\x1c.google.protobuf.FileOptionsR\ncompareAllB\0:C\n\x0ctypedecl_all\
    \x18\xb6\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x0bty\
    pedeclAllB\0:C\n\x0cenumdecl_all\x18\xb7\xec\x03\x20\x01(\x08\x12\x1c.go\
    ogle.protobuf.FileOptionsR\x0benumdeclAllB\0:S\n\x14goproto_registration\
    \x18\xb8\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x13go\
    protoRegistrationB\0:I\n\x0fmessagename_all\x18\xb9\xec\x03\x20\x01(\x08\
    \x12\x1c.google.protobuf.FileOptionsR\x0emessagenameAllB\0:T\n\x15goprot\
    o_sizecache_all\x18\xba\xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.Fil\
    eOptionsR\x13goprotoSizecacheAllB\0:P\n\x13goproto_unkeyed_all\x18\xbb\
    \xec\x03\x20\x01(\x08\x12\x1c.google.protobuf.FileOptionsR\x11goprotoUnk\
    eyedAllB\0:L\n\x0fgoproto_getters\x18\x81\xf4\x03\x20\x01(\x08\x12\x1f.g\
    oogle.protobuf.MessageOptionsR\x0egoprotoGettersB\0:N\n\x10goproto_strin\
    ger\x18\x83\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\
    \x0fgoprotoStringerB\0:H\n\rverbose_equal\x18\x84\xf4\x03\x20\x01(\x08\
    \x12\x1f.google.protobuf.MessageOptionsR\x0cverboseEqualB\0:7\n\x04face\
    \x18\x85\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\
    \x04faceB\0:?\n\x08gostring\x18\x86\xf4\x03\x20\x01(\x08\x12\x1f.google.\
    protobuf.MessageOptionsR\x08gostringB\0:?\n\x08populate\x18\x87\xf4\x03\
    \x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x08populateB\0:?\n\
    \x08stringer\x18\xc0\x8b\x04\x20\x01(\x08\x12\x1f.google.protobuf.Messag\
    eOptionsR\x08stringerB\0:=\n\x07onlyone\x18\x89\xf4\x03\x20\x01(\x08\x12\
    \x1f.google.protobuf.MessageOptionsR\x07onlyoneB\0:9\n\x05equal\x18\x8d\
    \xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x05equalB\
    \0:E\n\x0bdescription\x18\x8e\xf4\x03\x20\x01(\x08\x12\x1f.google.protob\
    uf.MessageOptionsR\x0bdescriptionB\0:=\n\x07testgen\x18\x8f\xf4\x03\x20\
    \x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x07testgenB\0:?\n\x08b\
    enchgen\x18\x90\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOpti\
    onsR\x08benchgenB\0:A\n\tmarshaler\x18\x91\xf4\x03\x20\x01(\x08\x12\x1f.\
    google.protobuf.MessageOptionsR\tmarshalerB\0:E\n\x0bunmarshaler\x18\x92\
    \xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x0bunmarsh\
    alerB\0:N\n\x10stable_marshaler\x18\x93\xf4\x03\x20\x01(\x08\x12\x1f.goo\
    gle.protobuf.MessageOptionsR\x0fstableMarshalerB\0:9\n\x05sizer\x18\x94\
    \xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x05sizerB\
    \0:N\n\x10unsafe_marshaler\x18\x97\xf4\x03\x20\x01(\x08\x12\x1f.google.p\
    rotobuf.MessageOptionsR\x0funsafeMarshalerB\0:R\n\x12unsafe_unmarshaler\
    \x18\x98\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\
    \x11unsafeUnmarshalerB\0:Y\n\x16goproto_extensions_map\x18\x99\xf4\x03\
    \x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x14goprotoExtensio\
    nsMapB\0:V\n\x14goproto_unrecognized\x18\x9a\xf4\x03\x20\x01(\x08\x12\
    \x1f.google.protobuf.MessageOptionsR\x13goprotoUnrecognizedB\0:C\n\nprot\
    osizer\x18\x9c\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptio\
    nsR\nprotosizerB\0:=\n\x07compare\x18\x9d\xf4\x03\x20\x01(\x08\x12\x1f.g\
    oogle.protobuf.MessageOptionsR\x07compareB\0:?\n\x08typedecl\x18\x9e\xf4\
    \x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x08typedeclB\0\
    :E\n\x0bmessagename\x18\xa1\xf4\x03\x20\x01(\x08\x12\x1f.google.protobuf\
    .MessageOptionsR\x0bmessagenameB\0:P\n\x11goproto_sizecache\x18\xa2\xf4\
    \x03\x20\x01(\x08\x12\x1f.google.protobuf.MessageOptionsR\x10goprotoSize\
    cacheB\0:L\n\x0fgoproto_unkeyed\x18\xa3\xf4\x03\x20\x01(\x08\x12\x1f.goo\
    gle.protobuf.MessageOptionsR\x0egoprotoUnkeyedB\0:=\n\x08nullable\x18\
    \xe9\xfb\x03\x20\x01(\x08\x12\x1d.google.protobuf.FieldOptionsR\x08nulla\
    bleB\0:7\n\x05embed\x18\xea\xfb\x03\x20\x01(\x08\x12\x1d.google.protobuf\
    .FieldOptionsR\x05embedB\0:A\n\ncustomtype\x18\xeb\xfb\x03\x20\x01(\t\
    \x12\x1d.google.protobuf.FieldOptionsR\ncustomtypeB\0:A\n\ncustomname\
    \x18\xec\xfb\x03\x20\x01(\t\x12\x1d.google.protobuf.FieldOptionsR\ncusto\
    mnameB\0:;\n\x07jsontag\x18\xed\xfb\x03\x20\x01(\t\x12\x1d.google.protob\
    uf.FieldOptionsR\x07jsontagB\0:=\n\x08moretags\x18\xee\xfb\x03\x20\x01(\
    \t\x12\x1d.google.protobuf.FieldOptionsR\x08moretagsB\0:=\n\x08casttype\
    \x18\xef\xfb\x03\x20\x01(\t\x12\x1d.google.protobuf.FieldOptionsR\x08cas\
    ttypeB\0:;\n\x07castkey\x18\xf0\xfb\x03\x20\x01(\t\x12\x1d.google.protob\
    uf.FieldOptionsR\x07castkeyB\0:?\n\tcastvalue\x18\xf1\xfb\x03\x20\x01(\t\
    \x12\x1d.google.protobuf.FieldOptionsR\tcastvalueB\0:;\n\x07stdtime\x18\
    \xf2\xfb\x03\x20\x01(\x08\x12\x1d.google.protobuf.FieldOptionsR\x07stdti\
    meB\0:C\n\x0bstdduration\x18\xf3\xfb\x03\x20\x01(\x08\x12\x1d.google.pro\
    tobuf.FieldOptionsR\x0bstddurationB\0:A\n\nwktpointer\x18\xf4\xfb\x03\
    \x20\x01(\x08\x12\x1d.google.protobuf.FieldOptionsR\nwktpointerB\0B\0b\
    \x06proto2\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
